name: Build pkgdown site
on:
  workflow_dispatch:
  push:
    branches:
    - devel
    - RELEASE_**

concurrency:
  group: pkgdown
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    name: Build pkgdown site
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup R
        uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
        with:
          r-version: renv
      - name: Install system dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          libcurl4-openssl-dev libssl-dev \
          libxml2-dev libgdal-dev libgit2-dev \
          libudunits2-dev libharfbuzz-dev libfribidi-dev \
          pandoc
      - name: Install dependencies
        uses: r-lib/actions/setup-renv@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      - name: Build pkgdown site
        run: Rscript -e 'pkgdown::build_site_github_pages(install = TRUE)'
      - name: Deploy pkgdown site
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: docs/
      - name: Deploy pkgdown site
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
