name: Build pkgdown site
on:
  workflow_dispatch:
  push:
    branches:
    - devel
    - RELEASE_**

concurrency:
  group: pkgdown
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    name: Build pkgdown site
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup R
        uses: r-lib/actions/setup-r@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2.13.0
        with:
          r-version: renv
      - name: Install system dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          libcurl4-openssl-dev libssl-dev \
          libxml2-dev libgdal-dev libgit2-dev \
          libudunits2-dev libharfbuzz-dev libfribidi-dev \
          pandoc
      - name: Install dependencies
        uses: r-lib/actions/setup-renv@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2.13.0
      - name: Build pkgdown site
        run: Rscript -e 'pkgdown::build_site_github_pages(install = TRUE)'
      - name: Deploy pkgdown site
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: docs/
      - name: Deploy pkgdown site
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
