name: Build pkgdown site
on:
  workflow_dispatch:
  push:
    branches:
    - devel
    - RELEASE_**

concurrency:
  group: pkgdown
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    name: Build pkgdown site
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Setup R
        uses: r-lib/actions/setup-r@e6be4b3706e0f39bc7a4cf4496a5f2c4cb840040 # v2.10.1
        with:
          r-version: renv
      - name: Install system dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          libcurl4-openssl-dev libssl-dev \
          libxml2-dev libgdal-dev libgit2-dev \
          libudunits2-dev libharfbuzz-dev libfribidi-dev \
          pandoc
      - name: Install dependencies
        uses: r-lib/actions/setup-renv@e6be4b3706e0f39bc7a4cf4496a5f2c4cb840040 # v2.10.1
      - name: Build pkgdown site
        run: Rscript -e 'pkgdown::build_site_github_pages(install = TRUE)'
      - name: Deploy pkgdown site
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: docs/
      - name: Deploy pkgdown site
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
